namespace FatturaElettronica.Tabelle
{
    public class IdPaese : Tabella
    {
        public override Tabella[] List
        {
            get
            {
                return new Tabella[] {
                    new IdPaese { Nome = "Afghanistan", Codice = "AF" },
                    new IdPaese { Nome = "Isole Åland", Codice = "AX" },
                    new IdPaese { Nome = "Albania", Codice = "AL" },
                    new IdPaese { Nome = "Algeria", Codice = "DZ" },
                    new IdPaese { Nome = "Samoa Americane", Codice = "AS" },
                    new IdPaese { Nome = "Andorra", Codice = "AD" },
                    new IdPaese { Nome = "Angola", Codice = "AO" },
                    new IdPaese { Nome = "Anguilla", Codice = "AI" },
                    new IdPaese { Nome = "Antartide", Codice = "AQ" },
                    new IdPaese { Nome = "Antigua e Barbuda", Codice = "AG" },
                    new IdPaese { Nome = "Argentina", Codice = "AR" },
                    new IdPaese { Nome = "Armenia", Codice = "AM" },
                    new IdPaese { Nome = "Aruba", Codice = "AW" },
                    new IdPaese { Nome = "Australia", Codice = "AU" },
                    new IdPaese { Nome = "Austria", Codice = "AT" },
                    new IdPaese { Nome = "Azerbaigian", Codice = "AZ" },
                    new IdPaese { Nome = "Bahamas", Codice = "BS" },
                    new IdPaese { Nome = "Bahrein", Codice = "BH" },
                    new IdPaese { Nome = "Bangladesh", Codice = "BD" },
                    new IdPaese { Nome = "Barbados", Codice = "BB" },
                    new IdPaese { Nome = "Bielorussia", Codice = "BY" },
                    new IdPaese { Nome = "Belgio", Codice = "BE" },
                    new IdPaese { Nome = "Belize", Codice = "BZ" },
                    new IdPaese { Nome = "Benin", Codice = "BJ" },
                    new IdPaese { Nome = "Bermuda", Codice = "BM" },
                    new IdPaese { Nome = "Bhutan", Codice = "BT" },
                    new IdPaese { Nome = "Bolivia", Codice = "BO" },
                    new IdPaese { Nome = "Isole BES", Codice = "BQ" },
                    new IdPaese { Nome = "Bosnia ed Erzegovina", Codice = "BA" },
                    new IdPaese { Nome = "Botswana", Codice = "BW" },
                    new IdPaese { Nome = "Isola Bouvet", Codice = "BV" },
                    new IdPaese { Nome = "Brasile", Codice = "BR" },
                    new IdPaese { Nome = "Territori Britannici dell'Oceano Indiano", Codice = "IO" },
                    new IdPaese { Nome = "Brunei", Codice = "BN" },
                    new IdPaese { Nome = "Bulgaria", Codice = "BG" },
                    new IdPaese { Nome = "Burkina Faso", Codice = "BF" },
                    new IdPaese { Nome = "Burundi", Codice = "BI" },
                    new IdPaese { Nome = "Cambogia", Codice = "KH" },
                    new IdPaese { Nome = "Camerun", Codice = "CM" },
                    new IdPaese { Nome = "Canada", Codice = "CA" },
                    new IdPaese { Nome = "Capo Verde", Codice = "CV" },
                    new IdPaese { Nome = "Isole Cayman", Codice = "KY" },
                    new IdPaese { Nome = "Repubblica Centrafricana", Codice = "CF" },
                    new IdPaese { Nome = "Ciad", Codice = "TD" },
                    new IdPaese { Nome = "Cile", Codice = "CL" },
                    new IdPaese { Nome = "Cina", Codice = "CN" },
                    new IdPaese { Nome = "Isola del Natale", Codice = "CX" },
                    new IdPaese { Nome = "Isole Cocos e Keeling", Codice = "CC" },
                    new IdPaese { Nome = "Colombia", Codice = "CO" },
                    new IdPaese { Nome = "Comore", Codice = "KM" },
                    new IdPaese { Nome = "Congo", Codice = "CG" },
                    new IdPaese { Nome = "Repubblica Democratica del Congo", Codice = "CD" },
                    new IdPaese { Nome = "Isole Cook", Codice = "CK" },
                    new IdPaese { Nome = "Costa Rica", Codice = "CR" },
                    new IdPaese { Nome = "Costa d'Avorio", Codice = "CI" },
                    new IdPaese { Nome = "Croazia", Codice = "HR" },
                    new IdPaese { Nome = "Cuba", Codice = "CU" },
                    new IdPaese { Nome = "Curaçao", Codice = "CW" },
                    new IdPaese { Nome = "Cipro", Codice = "CY" },
                    new IdPaese { Nome = "Cechia", Codice = "CZ" },
                    new IdPaese { Nome = "Danimarka", Codice = "DK" },
                    new IdPaese { Nome = "Gibuti", Codice = "DJ" },
                    new IdPaese { Nome = "Dominica", Codice = "DM" },
                    new IdPaese { Nome = "Repubblica Dominicana", Codice = "DO" },
                    new IdPaese { Nome = "Ecuador", Codice = "EC" },
                    new IdPaese { Nome = "Egitto", Codice = "EG" },
                    new IdPaese { Nome = "El Salvador", Codice = "SV" },
                    new IdPaese { Nome = "Guinea Equatoriale", Codice = "GQ" },
                    new IdPaese { Nome = "Eritrea", Codice = "ER" },
                    new IdPaese { Nome = "Estonia", Codice = "EE" },
                    new IdPaese { Nome = "Etiopia", Codice = "ET" },
                    new IdPaese { Nome = "Isole Falkland", Codice = "FK" },
                    new IdPaese { Nome = "Isole Fær Øer", Codice = "FO" },
                    new IdPaese { Nome = "Figi", Codice = "FJ" },
                    new IdPaese { Nome = "Finlandia", Codice = "FI" },
                    new IdPaese { Nome = "Francia", Codice = "FR" },
                    new IdPaese { Nome = "Guyana Francese", Codice = "GF" },
                    new IdPaese { Nome = "Polinesia Francese", Codice = "PF" },
                    new IdPaese { Nome = "Territori Francesi del Sud", Codice = "TF" },
                    new IdPaese { Nome = "Gabon", Codice = "GA" },
                    new IdPaese { Nome = "Gambia", Codice = "GM" },
                    new IdPaese { Nome = "Georgia", Codice = "GE" },
                    new IdPaese { Nome = "Germania", Codice = "DE" },
                    new IdPaese { Nome = "Ghana", Codice = "GH" },
                    new IdPaese { Nome = "Gibilterra", Codice = "GI" },
                    new IdPaese { Nome = "Grecia", Codice = "GR" },
                    new IdPaese { Nome = "Groenlandia", Codice = "GL" },
                    new IdPaese { Nome = "Grenada", Codice = "GD" },
                    new IdPaese { Nome = "Guadalupa", Codice = "GP" },
                    new IdPaese { Nome = "Guam", Codice = "GU" },
                    new IdPaese { Nome = "Guatemala", Codice = "GT" },
                    new IdPaese { Nome = "Guernsey", Codice = "GG" },
                    new IdPaese { Nome = "Guinea", Codice = "GN" },
                    new IdPaese { Nome = "Guinea-Bissau", Codice = "GW" },
                    new IdPaese { Nome = "Guyana", Codice = "GY" },
                    new IdPaese { Nome = "Haiti", Codice = "HT" },
                    new IdPaese { Nome = "Isole Heard e McDonald", Codice = "HM" },
                    new IdPaese { Nome = "Città del Vaticano", Codice = "VA" },
                    new IdPaese { Nome = "Honduras", Codice = "HN" },
                    new IdPaese { Nome = "Hong Kong", Codice = "HK" },
                    new IdPaese { Nome = "Ungheria", Codice = "HU" },
                    new IdPaese { Nome = "Islanda", Codice = "IS" },
                    new IdPaese { Nome = "India", Codice = "IN" },
                    new IdPaese { Nome = "Indonesia", Codice = "ID" },
                    new IdPaese { Nome = "Iran", Codice = "IR" },
                    new IdPaese { Nome = "Iraq", Codice = "IQ" },
                    new IdPaese { Nome = "Irlanda", Codice = "IE" },
                    new IdPaese { Nome = "Isola di Man", Codice = "IM" },
                    new IdPaese { Nome = "Israele", Codice = "IL" },
                    new IdPaese { Nome = "Italia", Codice = "IT" },
                    new IdPaese { Nome = "Giamaica", Codice = "JM" },
                    new IdPaese { Nome = "Giappone", Codice = "JP" },
                    new IdPaese { Nome = "Jersey", Codice = "JE" },
                    new IdPaese { Nome = "Giordania", Codice = "JO" },
                    new IdPaese { Nome = "Kazakistan", Codice = "KZ" },
                    new IdPaese { Nome = "Kenya", Codice = "KE" },
                    new IdPaese { Nome = "Kiribati", Codice = "KI" },
                    new IdPaese { Nome = "Corea del Nord", Codice = "KP" },
                    new IdPaese { Nome = "Corea del Sud", Codice = "KR" },
                    new IdPaese { Nome = "Kuwait", Codice = "KW" },
                    new IdPaese { Nome = "Kirghizistan", Codice = "KG" },
                    new IdPaese { Nome = "Laos", Codice = "LA" },
                    new IdPaese { Nome = "Lettonia", Codice = "LV" },
                    new IdPaese { Nome = "Libano", Codice = "LB" },
                    new IdPaese { Nome = "Lesotho", Codice = "LS" },
                    new IdPaese { Nome = "Liberia", Codice = "LR" },
                    new IdPaese { Nome = "Libia", Codice = "LY" },
                    new IdPaese { Nome = "Liechtenstein", Codice = "LI" },
                    new IdPaese { Nome = "Lituania", Codice = "LT" },
                    new IdPaese { Nome = "Lussemburgo", Codice = "LU" },
                    new IdPaese { Nome = "Macao", Codice = "MO" },
                    new IdPaese { Nome = "Macedonia", Codice = "MK" },
                    new IdPaese { Nome = "Madagascar", Codice = "MG" },
                    new IdPaese { Nome = "Malawi", Codice = "MW" },
                    new IdPaese { Nome = "Malesia", Codice = "MY" },
                    new IdPaese { Nome = "Maldive", Codice = "MV" },
                    new IdPaese { Nome = "Mali", Codice = "ML" },
                    new IdPaese { Nome = "Malta", Codice = "MT" },
                    new IdPaese { Nome = "Isole Marshall", Codice = "MH" },
                    new IdPaese { Nome = "Martinica", Codice = "MQ" },
                    new IdPaese { Nome = "Mauritania", Codice = "MR" },
                    new IdPaese { Nome = "Mauritius", Codice = "MU" },
                    new IdPaese { Nome = "Mayotte", Codice = "YT" },
                    new IdPaese { Nome = "Messico", Codice = "MX" },
                    new IdPaese { Nome = "Micronesia", Codice = "FM" },
                    new IdPaese { Nome = "Moldavia", Codice = "MD" },
                    new IdPaese { Nome = "Monaco", Codice = "MC" },
                    new IdPaese { Nome = "Mongolia", Codice = "MN" },
                    new IdPaese { Nome = "Montenegro", Codice = "ME" },
                    new IdPaese { Nome = "Montserrat", Codice = "MS" },
                    new IdPaese { Nome = "Marocco", Codice = "MA" },
                    new IdPaese { Nome = "Mozambico", Codice = "MZ" },
                    new IdPaese { Nome = "Birmania", Codice = "MM" },
                    new IdPaese { Nome = "Namibia", Codice = "NA" },
                    new IdPaese { Nome = "Nauru", Codice = "NR" },
                    new IdPaese { Nome = "Nepal", Codice = "NP" },
                    new IdPaese { Nome = "Paesi Bassi", Codice = "NL" },
                    new IdPaese { Nome = "Nuova Caledonia", Codice = "NC" },
                    new IdPaese { Nome = "Nuova Zelanda", Codice = "NZ" },
                    new IdPaese { Nome = "Nicaragua", Codice = "NI" },
                    new IdPaese { Nome = "Niger", Codice = "NE" },
                    new IdPaese { Nome = "Nigeria", Codice = "NG" },
                    new IdPaese { Nome = "Niue", Codice = "NU" },
                    new IdPaese { Nome = "Isole Norfolk", Codice = "NF" },
                    new IdPaese { Nome = "Isole Marianne Settentrionali", Codice = "MP" },
                    new IdPaese { Nome = "Norvegia", Codice = "NO" },
                    new IdPaese { Nome = "Oman", Codice = "OM" },
                    new IdPaese { Nome = "Pakistan", Codice = "PK" },
                    new IdPaese { Nome = "Palau", Codice = "PW" },
                    new IdPaese { Nome = "Stato di Palestina", Codice = "PS" },
                    new IdPaese { Nome = "Panama", Codice = "PA" },
                    new IdPaese { Nome = "Papua Nuova Guinea", Codice = "PG" },
                    new IdPaese { Nome = "Paraguay", Codice = "PY" },
                    new IdPaese { Nome = "Perù", Codice = "PE" },
                    new IdPaese { Nome = "Filippine", Codice = "PH" },
                    new IdPaese { Nome = "Isole Pitcairn", Codice = "PN" },
                    new IdPaese { Nome = "Polonia", Codice = "PL" },
                    new IdPaese { Nome = "Portogallo", Codice = "PT" },
                    new IdPaese { Nome = "Porto Rico", Codice = "PR" },
                    new IdPaese { Nome = "Qatar", Codice = "QA" },
                    new IdPaese { Nome = "Réunion", Codice = "RE" },
                    new IdPaese { Nome = "Romania", Codice = "RO" },
                    new IdPaese { Nome = "Russia", Codice = "RU" },
                    new IdPaese { Nome = "Ruanda", Codice = "RW" },
                    new IdPaese { Nome = "Saint-Barthélemy", Codice = "BL" },
                    new IdPaese { Nome = "Sant'Elena, Isola di Acensione e Tristan da Cunha", Codice = "SH" },
                    new IdPaese { Nome = "Saint Kitts e Nevis", Codice = "KN" },
                    new IdPaese { Nome = "Santa Lucia", Codice = "LC" },
                    new IdPaese { Nome = "Saint-Martin", Codice = "MF" },
                    new IdPaese { Nome = "Saint-Pierre e Miquelon", Codice = "PM" },
                    new IdPaese { Nome = "Saint Vincent e Grenadine", Codice = "VC" },
                    new IdPaese { Nome = "Samoa", Codice = "WS" },
                    new IdPaese { Nome = "San Marino", Codice = "SM" },
                    new IdPaese { Nome = "Sao Tome e Principe", Codice = "ST" },
                    new IdPaese { Nome = "Arabia Saudita", Codice = "SA" },
                    new IdPaese { Nome = "Senegal", Codice = "SN" },
                    new IdPaese { Nome = "Serbia", Codice = "RS" },
                    new IdPaese { Nome = "Seychelles", Codice = "SC" },
                    new IdPaese { Nome = "Sierra Leone", Codice = "SL" },
                    new IdPaese { Nome = "Singapore", Codice = "SG" },
                    new IdPaese { Nome = "Sint Maarten", Codice = "SX" },
                    new IdPaese { Nome = "Slovacchia", Codice = "SK" },
                    new IdPaese { Nome = "Slovenia", Codice = "SI" },
                    new IdPaese { Nome = "Isole Solomon", Codice = "SB" },
                    new IdPaese { Nome = "Somalia", Codice = "SO" },
                    new IdPaese { Nome = "Sud Africa", Codice = "ZA" },
                    new IdPaese { Nome = "Georgia del Sud e Isole Sandwich meridionali", Codice = "GS" },
                    new IdPaese { Nome = "Sudan del Sud", Codice = "SS" },
                    new IdPaese { Nome = "Spagna", Codice = "ES" },
                    new IdPaese { Nome = "Sri Lanka", Codice = "LK" },
                    new IdPaese { Nome = "Sudan", Codice = "SD" },
                    new IdPaese { Nome = "Suriname", Codice = "SR" },
                    new IdPaese { Nome = "Svalbard e Jan Mayen", Codice = "SJ" },
                    new IdPaese { Nome = "Swaziland", Codice = "SZ" },
                    new IdPaese { Nome = "Svezia", Codice = "SE" },
                    new IdPaese { Nome = "Svizzera", Codice = "CH" },
                    new IdPaese { Nome = "Siria", Codice = "SY" },
                    new IdPaese { Nome = "Taiwan (Repubblica di Cina)", Codice = "TW" },
                    new IdPaese { Nome = "Tagikistan", Codice = "TJ" },
                    new IdPaese { Nome = "Tanzania", Codice = "TZ" },
                    new IdPaese { Nome = "Tailandia", Codice = "TH" },
                    new IdPaese { Nome = "Timor Est", Codice = "TL" },
                    new IdPaese { Nome = "Togo", Codice = "TG" },
                    new IdPaese { Nome = "Tokelau", Codice = "TK" },
                    new IdPaese { Nome = "Tonga", Codice = "TO" },
                    new IdPaese { Nome = "Trinidad e Tobago", Codice = "TT" },
                    new IdPaese { Nome = "Tunisia", Codice = "TN" },
                    new IdPaese { Nome = "Turchia", Codice = "TR" },
                    new IdPaese { Nome = "Turkmenistan", Codice = "TM" },
                    new IdPaese { Nome = "Isole Turks e Caicos", Codice = "TC" },
                    new IdPaese { Nome = "Tuvalu", Codice = "TV" },
                    new IdPaese { Nome = "Uganda", Codice = "UG" },
                    new IdPaese { Nome = "Ucraina", Codice = "UA" },
                    new IdPaese { Nome = "Emirati Arabi Uniti", Codice = "AE" },
                    new IdPaese { Nome = "Regno Unito", Codice = "GB" },
                    new IdPaese { Nome = "Stati Uniti", Codice = "US" },
                    new IdPaese { Nome = "Isole Minor Esterne degli Stati Uniti", Codice = "UM" },
                    new IdPaese { Nome = "Uruguay", Codice = "UY" },
                    new IdPaese { Nome = "Uzbekistan", Codice = "UZ" },
                    new IdPaese { Nome = "Vanuatu", Codice = "VU" },
                    new IdPaese { Nome = "Venezuela", Codice = "VE" },
                    new IdPaese { Nome = "Vietnam", Codice = "VN" },
                    new IdPaese { Nome = "Isole Vergini britanniche", Codice = "VG" },
                    new IdPaese { Nome = "Isole Vergini americane", Codice = "VI" },
                    new IdPaese { Nome = "Wallis e Futuna", Codice = "WF" },
                    new IdPaese { Nome = "Sahara Occidentale", Codice = "EH" },
                    new IdPaese { Nome = "Yemen", Codice = "YE" },
                    new IdPaese { Nome = "Zambia", Codice = "ZM" },
                    new IdPaese { Nome = "Zimbabwe", Codice = "ZW" },
                };
            }
        }
    }
}