namespace FatturaElettronica.Tabelle
{
    public class IdPaese : Tabella
    {
        public override Tabella[] List
        {
            get
            {
                return new Tabella[] {
                    new IdPaese { Nome = "Afghanistan", Codice = "AF" },
                    new IdPaese { Nome = "Åland Islands", Codice = "AX" },
                    new IdPaese { Nome = "Albania", Codice = "AL" },
                    new IdPaese { Nome = "Algeria", Codice = "DZ" },
                    new IdPaese { Nome = "American Samoa", Codice = "AS" },
                    new IdPaese { Nome = "Andorra", Codice = "AD" },
                    new IdPaese { Nome = "Angola", Codice = "AO" },
                    new IdPaese { Nome = "Anguilla", Codice = "AI" },
                    new IdPaese { Nome = "Antarctica", Codice = "AQ" },
                    new IdPaese { Nome = "Antigua and Barbuda", Codice = "AG" },
                    new IdPaese { Nome = "Argentina", Codice = "AR" },
                    new IdPaese { Nome = "Armenia", Codice = "AM" },
                    new IdPaese { Nome = "Aruba", Codice = "AW" },
                    new IdPaese { Nome = "Australia", Codice = "AU" },
                    new IdPaese { Nome = "Austria", Codice = "AT" },
                    new IdPaese { Nome = "Azerbaijan", Codice = "AZ" },
                    new IdPaese { Nome = "Bahamas", Codice = "BS" },
                    new IdPaese { Nome = "Bahrain", Codice = "BH" },
                    new IdPaese { Nome = "Bangladesh", Codice = "BD" },
                    new IdPaese { Nome = "Barbados", Codice = "BB" },
                    new IdPaese { Nome = "Belarus", Codice = "BY" },
                    new IdPaese { Nome = "Belgium", Codice = "BE" },
                    new IdPaese { Nome = "Belize", Codice = "BZ" },
                    new IdPaese { Nome = "Benin", Codice = "BJ" },
                    new IdPaese { Nome = "Bermuda", Codice = "BM" },
                    new IdPaese { Nome = "Bhutan", Codice = "BT" },
                    new IdPaese { Nome = "Bolivia, Plurinational State of", Codice = "BO" },
                    new IdPaese { Nome = "Bonaire, Sint Eustatius and Saba", Codice = "BQ" },
                    new IdPaese { Nome = "Bosnia and Herzegovina", Codice = "BA" },
                    new IdPaese { Nome = "Botswana", Codice = "BW" },
                    new IdPaese { Nome = "Bouvet Island", Codice = "BV" },
                    new IdPaese { Nome = "Brazil", Codice = "BR" },
                    new IdPaese { Nome = "British Indian Ocean Territory", Codice = "IO" },
                    new IdPaese { Nome = "Brunei Darussalam", Codice = "BN" },
                    new IdPaese { Nome = "Bulgaria", Codice = "BG" },
                    new IdPaese { Nome = "Burkina Faso", Codice = "BF" },
                    new IdPaese { Nome = "Burundi", Codice = "BI" },
                    new IdPaese { Nome = "Cambodia", Codice = "KH" },
                    new IdPaese { Nome = "Cameroon", Codice = "CM" },
                    new IdPaese { Nome = "Canada", Codice = "CA" },
                    new IdPaese { Nome = "Cape Verde", Codice = "CV" },
                    new IdPaese { Nome = "Cayman Islands", Codice = "KY" },
                    new IdPaese { Nome = "Central African Republic", Codice = "CF" },
                    new IdPaese { Nome = "Chad", Codice = "TD" },
                    new IdPaese { Nome = "Chile", Codice = "CL" },
                    new IdPaese { Nome = "China", Codice = "CN" },
                    new IdPaese { Nome = "Christmas Island", Codice = "CX" },
                    new IdPaese { Nome = "Cocos (Keeling) Islands", Codice = "CC" },
                    new IdPaese { Nome = "Colombia", Codice = "CO" },
                    new IdPaese { Nome = "Comoros", Codice = "KM" },
                    new IdPaese { Nome = "Congo", Codice = "CG" },
                    new IdPaese { Nome = "Congo, the Democratic Republic of the", Codice = "CD" },
                    new IdPaese { Nome = "Cook Islands", Codice = "CK" },
                    new IdPaese { Nome = "Costa Rica", Codice = "CR" },
                    new IdPaese { Nome = "Côte d'Ivoire", Codice = "CI" },
                    new IdPaese { Nome = "Croatia", Codice = "HR" },
                    new IdPaese { Nome = "Cuba", Codice = "CU" },
                    new IdPaese { Nome = "Curaçao", Codice = "CW" },
                    new IdPaese { Nome = "Cyprus", Codice = "CY" },
                    new IdPaese { Nome = "Czech Republic", Codice = "CZ" },
                    new IdPaese { Nome = "Denmark", Codice = "DK" },
                    new IdPaese { Nome = "Djibouti", Codice = "DJ" },
                    new IdPaese { Nome = "Dominica", Codice = "DM" },
                    new IdPaese { Nome = "Dominican Republic", Codice = "DO" },
                    new IdPaese { Nome = "Ecuador", Codice = "EC" },
                    new IdPaese { Nome = "Egypt", Codice = "EG" },
                    new IdPaese { Nome = "El Salvador", Codice = "SV" },
                    new IdPaese { Nome = "Equatorial Guinea", Codice = "GQ" },
                    new IdPaese { Nome = "Eritrea", Codice = "ER" },
                    new IdPaese { Nome = "Estonia", Codice = "EE" },
                    new IdPaese { Nome = "Ethiopia", Codice = "ET" },
                    new IdPaese { Nome = "Falkland Islands (Malvinas)", Codice = "FK" },
                    new IdPaese { Nome = "Faroe Islands", Codice = "FO" },
                    new IdPaese { Nome = "Fiji", Codice = "FJ" },
                    new IdPaese { Nome = "Finland", Codice = "FI" },
                    new IdPaese { Nome = "France", Codice = "FR" },
                    new IdPaese { Nome = "French Guiana", Codice = "GF" },
                    new IdPaese { Nome = "French Polynesia", Codice = "PF" },
                    new IdPaese { Nome = "French Southern Territories", Codice = "TF" },
                    new IdPaese { Nome = "Gabon", Codice = "GA" },
                    new IdPaese { Nome = "Gambia", Codice = "GM" },
                    new IdPaese { Nome = "Georgia", Codice = "GE" },
                    new IdPaese { Nome = "Germany", Codice = "DE" },
                    new IdPaese { Nome = "Ghana", Codice = "GH" },
                    new IdPaese { Nome = "Gibraltar", Codice = "GI" },
                    new IdPaese { Nome = "Greece", Codice = "GR" },
                    new IdPaese { Nome = "Greenland", Codice = "GL" },
                    new IdPaese { Nome = "Grenada", Codice = "GD" },
                    new IdPaese { Nome = "Guadeloupe", Codice = "GP" },
                    new IdPaese { Nome = "Guam", Codice = "GU" },
                    new IdPaese { Nome = "Guatemala", Codice = "GT" },
                    new IdPaese { Nome = "Guernsey", Codice = "GG" },
                    new IdPaese { Nome = "Guinea", Codice = "GN" },
                    new IdPaese { Nome = "Guinea-Bissau", Codice = "GW" },
                    new IdPaese { Nome = "Guyana", Codice = "GY" },
                    new IdPaese { Nome = "Haiti", Codice = "HT" },
                    new IdPaese { Nome = "Heard Island and McDonald Islands", Codice = "HM" },
                    new IdPaese { Nome = "Holy See (Vatican City State)", Codice = "VA" },
                    new IdPaese { Nome = "Honduras", Codice = "HN" },
                    new IdPaese { Nome = "Hong Kong", Codice = "HK" },
                    new IdPaese { Nome = "Hungary", Codice = "HU" },
                    new IdPaese { Nome = "Iceland", Codice = "IS" },
                    new IdPaese { Nome = "India", Codice = "IN" },
                    new IdPaese { Nome = "Indonesia", Codice = "ID" },
                    new IdPaese { Nome = "Iran, Islamic Republic of", Codice = "IR" },
                    new IdPaese { Nome = "Iraq", Codice = "IQ" },
                    new IdPaese { Nome = "Ireland", Codice = "IE" },
                    new IdPaese { Nome = "Isle of Man", Codice = "IM" },
                    new IdPaese { Nome = "Israel", Codice = "IL" },
                    new IdPaese { Nome = "Italy", Codice = "IT" },
                    new IdPaese { Nome = "Jamaica", Codice = "JM" },
                    new IdPaese { Nome = "Japan", Codice = "JP" },
                    new IdPaese { Nome = "Jersey", Codice = "JE" },
                    new IdPaese { Nome = "Jordan", Codice = "JO" },
                    new IdPaese { Nome = "Kazakhstan", Codice = "KZ" },
                    new IdPaese { Nome = "Kenya", Codice = "KE" },
                    new IdPaese { Nome = "Kiribati", Codice = "KI" },
                    new IdPaese { Nome = "Korea, Democratic People's Republic of", Codice = "KP" },
                    new IdPaese { Nome = "Korea, Republic of", Codice = "KR" },
                    new IdPaese { Nome = "Kuwait", Codice = "KW" },
                    new IdPaese { Nome = "Kyrgyzstan", Codice = "KG" },
                    new IdPaese { Nome = "Lao People's Democratic Republic", Codice = "LA" },
                    new IdPaese { Nome = "Latvia", Codice = "LV" },
                    new IdPaese { Nome = "Lebanon", Codice = "LB" },
                    new IdPaese { Nome = "Lesotho", Codice = "LS" },
                    new IdPaese { Nome = "Liberia", Codice = "LR" },
                    new IdPaese { Nome = "Libya", Codice = "LY" },
                    new IdPaese { Nome = "Liechtenstein", Codice = "LI" },
                    new IdPaese { Nome = "Lithuania", Codice = "LT" },
                    new IdPaese { Nome = "Luxembourg", Codice = "LU" },
                    new IdPaese { Nome = "Macao", Codice = "MO" },
                    new IdPaese { Nome = "Macedonia, the former Yugoslav Republic of", Codice = "MK" },
                    new IdPaese { Nome = "Madagascar", Codice = "MG" },
                    new IdPaese { Nome = "Malawi", Codice = "MW" },
                    new IdPaese { Nome = "Malaysia", Codice = "MY" },
                    new IdPaese { Nome = "Maldives", Codice = "MV" },
                    new IdPaese { Nome = "Mali", Codice = "ML" },
                    new IdPaese { Nome = "Malta", Codice = "MT" },
                    new IdPaese { Nome = "Marshall Islands", Codice = "MH" },
                    new IdPaese { Nome = "Martinique", Codice = "MQ" },
                    new IdPaese { Nome = "Mauritania", Codice = "MR" },
                    new IdPaese { Nome = "Mauritius", Codice = "MU" },
                    new IdPaese { Nome = "Mayotte", Codice = "YT" },
                    new IdPaese { Nome = "Mexico", Codice = "MX" },
                    new IdPaese { Nome = "Micronesia, Federated States of", Codice = "FM" },
                    new IdPaese { Nome = "Moldova, Republic of", Codice = "MD" },
                    new IdPaese { Nome = "Monaco", Codice = "MC" },
                    new IdPaese { Nome = "Mongolia", Codice = "MN" },
                    new IdPaese { Nome = "Montenegro", Codice = "ME" },
                    new IdPaese { Nome = "Montserrat", Codice = "MS" },
                    new IdPaese { Nome = "Morocco", Codice = "MA" },
                    new IdPaese { Nome = "Mozambique", Codice = "MZ" },
                    new IdPaese { Nome = "Myanmar", Codice = "MM" },
                    new IdPaese { Nome = "Namibia", Codice = "NA" },
                    new IdPaese { Nome = "Nauru", Codice = "NR" },
                    new IdPaese { Nome = "Nepal", Codice = "NP" },
                    new IdPaese { Nome = "Netherlands", Codice = "NL" },
                    new IdPaese { Nome = "New Caledonia", Codice = "NC" },
                    new IdPaese { Nome = "New Zealand", Codice = "NZ" },
                    new IdPaese { Nome = "Nicaragua", Codice = "NI" },
                    new IdPaese { Nome = "Niger", Codice = "NE" },
                    new IdPaese { Nome = "Nigeria", Codice = "NG" },
                    new IdPaese { Nome = "Niue", Codice = "NU" },
                    new IdPaese { Nome = "Norfolk Island", Codice = "NF" },
                    new IdPaese { Nome = "Northern Mariana Islands", Codice = "MP" },
                    new IdPaese { Nome = "Norway", Codice = "NO" },
                    new IdPaese { Nome = "Oman", Codice = "OM" },
                    new IdPaese { Nome = "Pakistan", Codice = "PK" },
                    new IdPaese { Nome = "Palau", Codice = "PW" },
                    new IdPaese { Nome = "Palestinian Territory, Occupied", Codice = "PS" },
                    new IdPaese { Nome = "Panama", Codice = "PA" },
                    new IdPaese { Nome = "Papua New Guinea", Codice = "PG" },
                    new IdPaese { Nome = "Paraguay", Codice = "PY" },
                    new IdPaese { Nome = "Peru", Codice = "PE" },
                    new IdPaese { Nome = "Philippines", Codice = "PH" },
                    new IdPaese { Nome = "Pitcairn", Codice = "PN" },
                    new IdPaese { Nome = "Poland", Codice = "PL" },
                    new IdPaese { Nome = "Portugal", Codice = "PT" },
                    new IdPaese { Nome = "Puerto Rico", Codice = "PR" },
                    new IdPaese { Nome = "Qatar", Codice = "QA" },
                    new IdPaese { Nome = "Réunion", Codice = "RE" },
                    new IdPaese { Nome = "Romania", Codice = "RO" },
                    new IdPaese { Nome = "Russian Federation", Codice = "RU" },
                    new IdPaese { Nome = "Rwanda", Codice = "RW" },
                    new IdPaese { Nome = "Saint Barthélemy", Codice = "BL" },
                    new IdPaese { Nome = "Saint Helena, Ascension and Tristan da Cunha", Codice = "SH" },
                    new IdPaese { Nome = "Saint Kitts and Nevis", Codice = "KN" },
                    new IdPaese { Nome = "Saint Lucia", Codice = "LC" },
                    new IdPaese { Nome = "Saint Martin (French part)", Codice = "MF" },
                    new IdPaese { Nome = "Saint Pierre and Miquelon", Codice = "PM" },
                    new IdPaese { Nome = "Saint Vincent and the Grenadines", Codice = "VC" },
                    new IdPaese { Nome = "Samoa", Codice = "WS" },
                    new IdPaese { Nome = "San Marino", Codice = "SM" },
                    new IdPaese { Nome = "Sao Tome and Principe", Codice = "ST" },
                    new IdPaese { Nome = "Saudi Arabia", Codice = "SA" },
                    new IdPaese { Nome = "Senegal", Codice = "SN" },
                    new IdPaese { Nome = "Serbia", Codice = "RS" },
                    new IdPaese { Nome = "Seychelles", Codice = "SC" },
                    new IdPaese { Nome = "Sierra Leone", Codice = "SL" },
                    new IdPaese { Nome = "Singapore", Codice = "SG" },
                    new IdPaese { Nome = "Sint Maarten (Dutch part)", Codice = "SX" },
                    new IdPaese { Nome = "Slovakia", Codice = "SK" },
                    new IdPaese { Nome = "Slovenia", Codice = "SI" },
                    new IdPaese { Nome = "Solomon Islands", Codice = "SB" },
                    new IdPaese { Nome = "Somalia", Codice = "SO" },
                    new IdPaese { Nome = "South Africa", Codice = "ZA" },
                    new IdPaese { Nome = "South Georgia and the South Sandwich Islands", Codice = "GS" },
                    new IdPaese { Nome = "South Sudan", Codice = "SS" },
                    new IdPaese { Nome = "Spain", Codice = "ES" },
                    new IdPaese { Nome = "Sri Lanka", Codice = "LK" },
                    new IdPaese { Nome = "Sudan", Codice = "SD" },
                    new IdPaese { Nome = "Suriname", Codice = "SR" },
                    new IdPaese { Nome = "Svalbard and Jan Mayen", Codice = "SJ" },
                    new IdPaese { Nome = "Swaziland", Codice = "SZ" },
                    new IdPaese { Nome = "Sweden", Codice = "SE" },
                    new IdPaese { Nome = "Switzerland", Codice = "CH" },
                    new IdPaese { Nome = "Syrian Arab Republic", Codice = "SY" },
                    new IdPaese { Nome = "Taiwan, Province of China", Codice = "TW" },
                    new IdPaese { Nome = "Tajikistan", Codice = "TJ" },
                    new IdPaese { Nome = "Tanzania, United Republic of", Codice = "TZ" },
                    new IdPaese { Nome = "Thailand", Codice = "TH" },
                    new IdPaese { Nome = "Timor-Leste", Codice = "TL" },
                    new IdPaese { Nome = "Togo", Codice = "TG" },
                    new IdPaese { Nome = "Tokelau", Codice = "TK" },
                    new IdPaese { Nome = "Tonga", Codice = "TO" },
                    new IdPaese { Nome = "Trinidad and Tobago", Codice = "TT" },
                    new IdPaese { Nome = "Tunisia", Codice = "TN" },
                    new IdPaese { Nome = "Turkey", Codice = "TR" },
                    new IdPaese { Nome = "Turkmenistan", Codice = "TM" },
                    new IdPaese { Nome = "Turks and Caicos Islands", Codice = "TC" },
                    new IdPaese { Nome = "Tuvalu", Codice = "TV" },
                    new IdPaese { Nome = "Uganda", Codice = "UG" },
                    new IdPaese { Nome = "Ukraine", Codice = "UA" },
                    new IdPaese { Nome = "United Arab Emirates", Codice = "AE" },
                    new IdPaese { Nome = "United Kingdom", Codice = "GB" },
                    new IdPaese { Nome = "United States", Codice = "US" },
                    new IdPaese { Nome = "United States Minor Outlying Islands", Codice = "UM" },
                    new IdPaese { Nome = "Uruguay", Codice = "UY" },
                    new IdPaese { Nome = "Uzbekistan", Codice = "UZ" },
                    new IdPaese { Nome = "Vanuatu", Codice = "VU" },
                    new IdPaese { Nome = "Venezuela, Bolivarian Republic of", Codice = "VE" },
                    new IdPaese { Nome = "Viet Nam", Codice = "VN" },
                    new IdPaese { Nome = "Virgin Islands, British", Codice = "VG" },
                    new IdPaese { Nome = "Virgin Islands, U.S.", Codice = "VI" },
                    new IdPaese { Nome = "Wallis and Futuna", Codice = "WF" },
                    new IdPaese { Nome = "Western Sahara", Codice = "EH" },
                    new IdPaese { Nome = "Yemen", Codice = "YE" },
                    new IdPaese { Nome = "Zambia", Codice = "ZM" },
                    new IdPaese { Nome = "Zimbabwe", Codice = "ZW" },
                };
            } 
        }
    }
}