//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FatturaElettronica.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ModalitaPagamento {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ModalitaPagamento() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FatturaElettronica.Resources.ModalitaPagamento", typeof(ModalitaPagamento).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to contanti.
        /// </summary>
        internal static string MP01 {
            get {
                return ResourceManager.GetString("MP01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to assegno.
        /// </summary>
        internal static string MP02 {
            get {
                return ResourceManager.GetString("MP02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to assegno circolare.
        /// </summary>
        internal static string MP03 {
            get {
                return ResourceManager.GetString("MP03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to contanti presso Tesoreria.
        /// </summary>
        internal static string MP04 {
            get {
                return ResourceManager.GetString("MP04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bonifico.
        /// </summary>
        internal static string MP05 {
            get {
                return ResourceManager.GetString("MP05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vaglia cambiario.
        /// </summary>
        internal static string MP06 {
            get {
                return ResourceManager.GetString("MP06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bollettino bancario.
        /// </summary>
        internal static string MP07 {
            get {
                return ResourceManager.GetString("MP07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to carta di pagamento.
        /// </summary>
        internal static string MP08 {
            get {
                return ResourceManager.GetString("MP08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RID.
        /// </summary>
        internal static string MP09 {
            get {
                return ResourceManager.GetString("MP09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RID utenze.
        /// </summary>
        internal static string MP10 {
            get {
                return ResourceManager.GetString("MP10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RID veloce.
        /// </summary>
        internal static string MP11 {
            get {
                return ResourceManager.GetString("MP11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RIBA.
        /// </summary>
        internal static string MP12 {
            get {
                return ResourceManager.GetString("MP12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAV.
        /// </summary>
        internal static string MP13 {
            get {
                return ResourceManager.GetString("MP13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to quietanza erario.
        /// </summary>
        internal static string MP14 {
            get {
                return ResourceManager.GetString("MP14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to giroconto su conti di contabilità speciale.
        /// </summary>
        internal static string MP15 {
            get {
                return ResourceManager.GetString("MP15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to domiciliazione bancaria.
        /// </summary>
        internal static string MP16 {
            get {
                return ResourceManager.GetString("MP16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to domiciliazione postale.
        /// </summary>
        internal static string MP17 {
            get {
                return ResourceManager.GetString("MP17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bollettino di c/c postale.
        /// </summary>
        internal static string MP18 {
            get {
                return ResourceManager.GetString("MP18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEPA Direct Debit.
        /// </summary>
        internal static string MP19 {
            get {
                return ResourceManager.GetString("MP19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEPA Direct Debit CORE.
        /// </summary>
        internal static string MP20 {
            get {
                return ResourceManager.GetString("MP20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEPA Direct Debit B2B.
        /// </summary>
        internal static string MP21 {
            get {
                return ResourceManager.GetString("MP21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trattenuta su somme già riscosse.
        /// </summary>
        internal static string MP22 {
            get {
                return ResourceManager.GetString("MP22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PagoPA.
        /// </summary>
        internal static string MP23 {
            get {
                return ResourceManager.GetString("MP23", resourceCulture);
            }
        }
    }
}
