//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FatturaElettronica.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Natura {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Natura() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FatturaElettronica.Resources.Natura", typeof(Natura).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to escluse ex art. 15.
        /// </summary>
        public static string N1 {
            get {
                return ResourceManager.GetString("N1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to non soggette ad IVA ai sensi degli artt. da 7 a 7-septies del DPR 633/72.
        /// </summary>
        public static string N2_1 {
            get {
                return ResourceManager.GetString("N2.1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to non soggette - altri casi.
        /// </summary>
        public static string N2_2 {
            get {
                return ResourceManager.GetString("N2.2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to non imponibili - esportazioni.
        /// </summary>
        public static string N3_1 {
            get {
                return ResourceManager.GetString("N3.1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to non imponibili - cessioni intracomunitarie.
        /// </summary>
        public static string N3_2 {
            get {
                return ResourceManager.GetString("N3.2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to non imponibili - cessioni verso San Marino.
        /// </summary>
        public static string N3_3 {
            get {
                return ResourceManager.GetString("N3.3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to non imponibili - operazioni assimilate alle cessioni all&apos;esportazione.
        /// </summary>
        public static string N3_4 {
            get {
                return ResourceManager.GetString("N3.4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to non imponibili - a seguito di dichiarazioni d&apos;intento.
        /// </summary>
        public static string N3_5 {
            get {
                return ResourceManager.GetString("N3.5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to non imponibili - altre operazioni che non concorrono alla formazione del plafond.
        /// </summary>
        public static string N3_6 {
            get {
                return ResourceManager.GetString("N3.6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to esenti.
        /// </summary>
        public static string N4 {
            get {
                return ResourceManager.GetString("N4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to regime del margine / IVA non esposta in fattura.
        /// </summary>
        public static string N5 {
            get {
                return ResourceManager.GetString("N5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to inversione contabile - cessione di rottami e altri materiali di recupero.
        /// </summary>
        public static string N6_1 {
            get {
                return ResourceManager.GetString("N6.1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to inversione contabile - inversione contabile – cessione di oro e argento ai sensi della legge 7/2000 nonché di oreficeria usata ad OPO.
        /// </summary>
        public static string N6_2 {
            get {
                return ResourceManager.GetString("N6.2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to inversione contabile - subappalto nel settore edile.
        /// </summary>
        public static string N6_3 {
            get {
                return ResourceManager.GetString("N6.3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to inversione contabile - cessione di fabbricati.
        /// </summary>
        public static string N6_4 {
            get {
                return ResourceManager.GetString("N6.4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to inversione contabile - cessione di telefoni cellulari.
        /// </summary>
        public static string N6_5 {
            get {
                return ResourceManager.GetString("N6.5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to inversione contabile - cessione di prodotti elettronici.
        /// </summary>
        public static string N6_6 {
            get {
                return ResourceManager.GetString("N6.6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to inversione contabile - prestazioni comparto edile e settori connessi.
        /// </summary>
        public static string N6_7 {
            get {
                return ResourceManager.GetString("N6.7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to inversione contabile - operazioni settore energetico.
        /// </summary>
        public static string N6_8 {
            get {
                return ResourceManager.GetString("N6.8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to inversione contabile - altri casi.
        /// </summary>
        public static string N6_9 {
            get {
                return ResourceManager.GetString("N6.9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IVA assolta in altro stato UE (prestazione di servizi di telecomunicazioni, tele-radiodiffusione ed elettronici ex art. 7-octies, comma 1 lett. a, b, art. 74-sexies DPR 633/72).
        /// </summary>
        public static string N7 {
            get {
                return ResourceManager.GetString("N7", resourceCulture);
            }
        }
    }
}
