//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FatturaElettronica.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class NaturaSemplificata {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NaturaSemplificata() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FatturaElettronica.Resources.NaturaSemplificata", typeof(NaturaSemplificata).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to escluse ex art. 15.
        /// </summary>
        internal static string N1 {
            get {
                return ResourceManager.GetString("N1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to non soggette.
        /// </summary>
        internal static string N2 {
            get {
                return ResourceManager.GetString("N2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to non soggette ad IVA ai sensi degli artt. da 7 a 7-septies del D.P.R. n. 633/72.
        /// </summary>
        internal static string N2_1 {
            get {
                return ResourceManager.GetString("N2.1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to non soggette - altri casi.
        /// </summary>
        internal static string N2_2 {
            get {
                return ResourceManager.GetString("N2.2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to non imponibili.
        /// </summary>
        internal static string N3 {
            get {
                return ResourceManager.GetString("N3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to non imponibili - esportazioni.
        /// </summary>
        internal static string N3_1 {
            get {
                return ResourceManager.GetString("N3.1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to non imponibili - cessioni intracomunitarie.
        /// </summary>
        internal static string N3_2 {
            get {
                return ResourceManager.GetString("N3.2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to non imponibili - cessioni verso San Marino.
        /// </summary>
        internal static string N3_3 {
            get {
                return ResourceManager.GetString("N3.3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to non imponibili - operazioni assimilate alle cessioni all&apos;esportazione.
        /// </summary>
        internal static string N3_4 {
            get {
                return ResourceManager.GetString("N3.4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to non imponibili - a seguito di dichiarazioni d&apos;intento.
        /// </summary>
        internal static string N3_5 {
            get {
                return ResourceManager.GetString("N3.5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to non imponibili - altre operazioni che non concorrono alla formazione del plafond.
        /// </summary>
        internal static string N3_6 {
            get {
                return ResourceManager.GetString("N3.6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to esenti.
        /// </summary>
        internal static string N4 {
            get {
                return ResourceManager.GetString("N4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to regime del margine / IVA non esposta in fattura.
        /// </summary>
        internal static string N5 {
            get {
                return ResourceManager.GetString("N5", resourceCulture);
            }
        }
    }
}
