//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FatturaElettronica.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Provincia {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Provincia() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FatturaElettronica.Resources.Provincia", typeof(Provincia).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agrigento.
        /// </summary>
        internal static string AG {
            get {
                return ResourceManager.GetString("AG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alessandria.
        /// </summary>
        internal static string AL {
            get {
                return ResourceManager.GetString("AL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ancona.
        /// </summary>
        internal static string AN {
            get {
                return ResourceManager.GetString("AN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aosta.
        /// </summary>
        internal static string AO {
            get {
                return ResourceManager.GetString("AO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ascoli-Piceno.
        /// </summary>
        internal static string AP {
            get {
                return ResourceManager.GetString("AP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;Aquila.
        /// </summary>
        internal static string AQ {
            get {
                return ResourceManager.GetString("AQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arezzo.
        /// </summary>
        internal static string AR {
            get {
                return ResourceManager.GetString("AR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asti.
        /// </summary>
        internal static string AT {
            get {
                return ResourceManager.GetString("AT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avellino.
        /// </summary>
        internal static string AV {
            get {
                return ResourceManager.GetString("AV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bari.
        /// </summary>
        internal static string BA {
            get {
                return ResourceManager.GetString("BA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bergamo.
        /// </summary>
        internal static string BG {
            get {
                return ResourceManager.GetString("BG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Biella.
        /// </summary>
        internal static string BI {
            get {
                return ResourceManager.GetString("BI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Belluno.
        /// </summary>
        internal static string BL {
            get {
                return ResourceManager.GetString("BL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benevento.
        /// </summary>
        internal static string BN {
            get {
                return ResourceManager.GetString("BN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bologna.
        /// </summary>
        internal static string BO {
            get {
                return ResourceManager.GetString("BO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brindisi.
        /// </summary>
        internal static string BR {
            get {
                return ResourceManager.GetString("BR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brescia.
        /// </summary>
        internal static string BS {
            get {
                return ResourceManager.GetString("BS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barletta-Andria-Trani.
        /// </summary>
        internal static string BT {
            get {
                return ResourceManager.GetString("BT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bolzano.
        /// </summary>
        internal static string BZ {
            get {
                return ResourceManager.GetString("BZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cagliari.
        /// </summary>
        internal static string CA {
            get {
                return ResourceManager.GetString("CA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campobasso.
        /// </summary>
        internal static string CB {
            get {
                return ResourceManager.GetString("CB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caserta.
        /// </summary>
        internal static string CE {
            get {
                return ResourceManager.GetString("CE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chieti.
        /// </summary>
        internal static string CH {
            get {
                return ResourceManager.GetString("CH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carbonia Iglesias.
        /// </summary>
        internal static string CI {
            get {
                return ResourceManager.GetString("CI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caltanissetta.
        /// </summary>
        internal static string CL {
            get {
                return ResourceManager.GetString("CL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cuneo.
        /// </summary>
        internal static string CN {
            get {
                return ResourceManager.GetString("CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Como.
        /// </summary>
        internal static string CO {
            get {
                return ResourceManager.GetString("CO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cremona.
        /// </summary>
        internal static string CR {
            get {
                return ResourceManager.GetString("CR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cosenza.
        /// </summary>
        internal static string CS {
            get {
                return ResourceManager.GetString("CS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catania.
        /// </summary>
        internal static string CT {
            get {
                return ResourceManager.GetString("CT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catanzaro.
        /// </summary>
        internal static string CZ {
            get {
                return ResourceManager.GetString("CZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enna.
        /// </summary>
        internal static string EN {
            get {
                return ResourceManager.GetString("EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forli-Cesena.
        /// </summary>
        internal static string FC {
            get {
                return ResourceManager.GetString("FC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ferrara.
        /// </summary>
        internal static string FE {
            get {
                return ResourceManager.GetString("FE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foggia.
        /// </summary>
        internal static string FG {
            get {
                return ResourceManager.GetString("FG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firenze.
        /// </summary>
        internal static string FI {
            get {
                return ResourceManager.GetString("FI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fermo.
        /// </summary>
        internal static string FM {
            get {
                return ResourceManager.GetString("FM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frosinone.
        /// </summary>
        internal static string FR {
            get {
                return ResourceManager.GetString("FR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genova.
        /// </summary>
        internal static string GE {
            get {
                return ResourceManager.GetString("GE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gorizia.
        /// </summary>
        internal static string GO {
            get {
                return ResourceManager.GetString("GO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grosseto.
        /// </summary>
        internal static string GR {
            get {
                return ResourceManager.GetString("GR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imperia.
        /// </summary>
        internal static string IM {
            get {
                return ResourceManager.GetString("IM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Isernia.
        /// </summary>
        internal static string IS {
            get {
                return ResourceManager.GetString("IS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crotone.
        /// </summary>
        internal static string KR {
            get {
                return ResourceManager.GetString("KR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lecco.
        /// </summary>
        internal static string LC {
            get {
                return ResourceManager.GetString("LC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lecce.
        /// </summary>
        internal static string LE {
            get {
                return ResourceManager.GetString("LE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Livorno.
        /// </summary>
        internal static string LI {
            get {
                return ResourceManager.GetString("LI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lodi.
        /// </summary>
        internal static string LO {
            get {
                return ResourceManager.GetString("LO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latina.
        /// </summary>
        internal static string LT {
            get {
                return ResourceManager.GetString("LT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lucca.
        /// </summary>
        internal static string LU {
            get {
                return ResourceManager.GetString("LU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monza-Brianza.
        /// </summary>
        internal static string MB {
            get {
                return ResourceManager.GetString("MB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Macerata.
        /// </summary>
        internal static string MC {
            get {
                return ResourceManager.GetString("MC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messina.
        /// </summary>
        internal static string ME {
            get {
                return ResourceManager.GetString("ME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Milano.
        /// </summary>
        internal static string MI {
            get {
                return ResourceManager.GetString("MI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mantova.
        /// </summary>
        internal static string MN {
            get {
                return ResourceManager.GetString("MN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modena.
        /// </summary>
        internal static string MO {
            get {
                return ResourceManager.GetString("MO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Massa-Carrara.
        /// </summary>
        internal static string MS {
            get {
                return ResourceManager.GetString("MS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matera.
        /// </summary>
        internal static string MT {
            get {
                return ResourceManager.GetString("MT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Napoli.
        /// </summary>
        internal static string NA {
            get {
                return ResourceManager.GetString("NA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novara.
        /// </summary>
        internal static string NO {
            get {
                return ResourceManager.GetString("NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuoro.
        /// </summary>
        internal static string NU {
            get {
                return ResourceManager.GetString("NU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ogliastra.
        /// </summary>
        internal static string OG {
            get {
                return ResourceManager.GetString("OG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oristano.
        /// </summary>
        internal static string OR {
            get {
                return ResourceManager.GetString("OR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Olbia Tempio.
        /// </summary>
        internal static string OT {
            get {
                return ResourceManager.GetString("OT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Palermo.
        /// </summary>
        internal static string PA {
            get {
                return ResourceManager.GetString("PA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Piacenza.
        /// </summary>
        internal static string PC {
            get {
                return ResourceManager.GetString("PC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Padova.
        /// </summary>
        internal static string PD {
            get {
                return ResourceManager.GetString("PD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pescara.
        /// </summary>
        internal static string PE {
            get {
                return ResourceManager.GetString("PE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perugia.
        /// </summary>
        internal static string PG {
            get {
                return ResourceManager.GetString("PG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pisa.
        /// </summary>
        internal static string PI {
            get {
                return ResourceManager.GetString("PI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pordenone.
        /// </summary>
        internal static string PN {
            get {
                return ResourceManager.GetString("PN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prato.
        /// </summary>
        internal static string PO {
            get {
                return ResourceManager.GetString("PO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parma.
        /// </summary>
        internal static string PR {
            get {
                return ResourceManager.GetString("PR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pistoia.
        /// </summary>
        internal static string PT {
            get {
                return ResourceManager.GetString("PT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pesaro-Urbino.
        /// </summary>
        internal static string PU {
            get {
                return ResourceManager.GetString("PU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pavia.
        /// </summary>
        internal static string PV {
            get {
                return ResourceManager.GetString("PV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potenza.
        /// </summary>
        internal static string PZ {
            get {
                return ResourceManager.GetString("PZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ravenna.
        /// </summary>
        internal static string RA {
            get {
                return ResourceManager.GetString("RA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reggio-Calabria.
        /// </summary>
        internal static string RC {
            get {
                return ResourceManager.GetString("RC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reggio-Emilia.
        /// </summary>
        internal static string RE {
            get {
                return ResourceManager.GetString("RE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ragusa.
        /// </summary>
        internal static string RG {
            get {
                return ResourceManager.GetString("RG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rieti.
        /// </summary>
        internal static string RI {
            get {
                return ResourceManager.GetString("RI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roma.
        /// </summary>
        internal static string RM {
            get {
                return ResourceManager.GetString("RM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rimini.
        /// </summary>
        internal static string RN {
            get {
                return ResourceManager.GetString("RN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rovigo.
        /// </summary>
        internal static string RO {
            get {
                return ResourceManager.GetString("RO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salerno.
        /// </summary>
        internal static string SA {
            get {
                return ResourceManager.GetString("SA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Siena.
        /// </summary>
        internal static string SI {
            get {
                return ResourceManager.GetString("SI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sondrio.
        /// </summary>
        internal static string SO {
            get {
                return ResourceManager.GetString("SO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La-Spezia.
        /// </summary>
        internal static string SP {
            get {
                return ResourceManager.GetString("SP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Siracusa.
        /// </summary>
        internal static string SR {
            get {
                return ResourceManager.GetString("SR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sassari.
        /// </summary>
        internal static string SS {
            get {
                return ResourceManager.GetString("SS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sud Sardegna.
        /// </summary>
        internal static string SU {
            get {
                return ResourceManager.GetString("SU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Savona.
        /// </summary>
        internal static string SV {
            get {
                return ResourceManager.GetString("SV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taranto.
        /// </summary>
        internal static string TA {
            get {
                return ResourceManager.GetString("TA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teramo.
        /// </summary>
        internal static string TE {
            get {
                return ResourceManager.GetString("TE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trento.
        /// </summary>
        internal static string TN {
            get {
                return ResourceManager.GetString("TN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Torino.
        /// </summary>
        internal static string TO {
            get {
                return ResourceManager.GetString("TO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trapani.
        /// </summary>
        internal static string TP {
            get {
                return ResourceManager.GetString("TP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terni.
        /// </summary>
        internal static string TR {
            get {
                return ResourceManager.GetString("TR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trieste.
        /// </summary>
        internal static string TS {
            get {
                return ResourceManager.GetString("TS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Treviso.
        /// </summary>
        internal static string TV {
            get {
                return ResourceManager.GetString("TV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Udine.
        /// </summary>
        internal static string UD {
            get {
                return ResourceManager.GetString("UD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Varese.
        /// </summary>
        internal static string VA {
            get {
                return ResourceManager.GetString("VA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verbania.
        /// </summary>
        internal static string VB {
            get {
                return ResourceManager.GetString("VB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vercelli.
        /// </summary>
        internal static string VC {
            get {
                return ResourceManager.GetString("VC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Venezia.
        /// </summary>
        internal static string VE {
            get {
                return ResourceManager.GetString("VE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vicenza.
        /// </summary>
        internal static string VI {
            get {
                return ResourceManager.GetString("VI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verona.
        /// </summary>
        internal static string VR {
            get {
                return ResourceManager.GetString("VR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medio Campidano.
        /// </summary>
        internal static string VS {
            get {
                return ResourceManager.GetString("VS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Viterbo.
        /// </summary>
        internal static string VT {
            get {
                return ResourceManager.GetString("VT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vibo-Valentia.
        /// </summary>
        internal static string VV {
            get {
                return ResourceManager.GetString("VV", resourceCulture);
            }
        }
    }
}
