//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FatturaElettronica.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RegimeFiscale {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RegimeFiscale() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("FatturaElettronica.Resources.RegimeFiscale", typeof(RegimeFiscale).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string RF01 {
            get {
                return ResourceManager.GetString("RF01", resourceCulture);
            }
        }
        
        public static string RF02 {
            get {
                return ResourceManager.GetString("RF02", resourceCulture);
            }
        }
        
        public static string RF04 {
            get {
                return ResourceManager.GetString("RF04", resourceCulture);
            }
        }
        
        public static string RF05 {
            get {
                return ResourceManager.GetString("RF05", resourceCulture);
            }
        }
        
        public static string RF06 {
            get {
                return ResourceManager.GetString("RF06", resourceCulture);
            }
        }
        
        public static string RF07 {
            get {
                return ResourceManager.GetString("RF07", resourceCulture);
            }
        }
        
        public static string RF08 {
            get {
                return ResourceManager.GetString("RF08", resourceCulture);
            }
        }
        
        public static string RF09 {
            get {
                return ResourceManager.GetString("RF09", resourceCulture);
            }
        }
        
        public static string RF10 {
            get {
                return ResourceManager.GetString("RF10", resourceCulture);
            }
        }
        
        public static string RF11 {
            get {
                return ResourceManager.GetString("RF11", resourceCulture);
            }
        }
        
        public static string RF12 {
            get {
                return ResourceManager.GetString("RF12", resourceCulture);
            }
        }
        
        public static string RF13 {
            get {
                return ResourceManager.GetString("RF13", resourceCulture);
            }
        }
        
        public static string RF14 {
            get {
                return ResourceManager.GetString("RF14", resourceCulture);
            }
        }
        
        public static string RF15 {
            get {
                return ResourceManager.GetString("RF15", resourceCulture);
            }
        }
        
        public static string RF16 {
            get {
                return ResourceManager.GetString("RF16", resourceCulture);
            }
        }
        
        public static string RF17 {
            get {
                return ResourceManager.GetString("RF17", resourceCulture);
            }
        }
        
        public static string RF18 {
            get {
                return ResourceManager.GetString("RF18", resourceCulture);
            }
        }
        
        public static string RF19 {
            get {
                return ResourceManager.GetString("RF19", resourceCulture);
            }
        }
        
        public static string RF20 {
            get {
                return ResourceManager.GetString("RF20", resourceCulture);
            }
        }
    }
}
