//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FatturaElettronica.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RegimeFiscale {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RegimeFiscale() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FatturaElettronica.Resources.RegimeFiscale", typeof(RegimeFiscale).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ordinario.
        /// </summary>
        public static string RF01 {
            get {
                return ResourceManager.GetString("RF01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contribuenti minimi (art.1, c.96-117, L. 244/07 ).
        /// </summary>
        public static string RF02 {
            get {
                return ResourceManager.GetString("RF02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agricoltura e attività connesse e pesca (artt.34 e 34-bis, DPR 633/72 ).
        /// </summary>
        public static string RF04 {
            get {
                return ResourceManager.GetString("RF04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendita sali e tabacchi (art.74, c.1, DPR 633/72 ).
        /// </summary>
        public static string RF05 {
            get {
                return ResourceManager.GetString("RF05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commercio fiammiferi (art.74, c.1, DPR 633/72 ).
        /// </summary>
        public static string RF06 {
            get {
                return ResourceManager.GetString("RF06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editoria (art.74, c.1, DPR 633/72 ).
        /// </summary>
        public static string RF07 {
            get {
                return ResourceManager.GetString("RF07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestione servizi telefonia pubblica (art.74, c.1, DPR 633/72 ).
        /// </summary>
        public static string RF08 {
            get {
                return ResourceManager.GetString("RF08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rivendita documenti di trasporto pubblico e di sosta (art.74, c.1, DPR 633/72 ).
        /// </summary>
        public static string RF09 {
            get {
                return ResourceManager.GetString("RF09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intrattenimenti, giochi e altre attività di cui all atariffa allegata al DPR 640/72 (art.74, c.6, DPR 633/72 ).
        /// </summary>
        public static string RF10 {
            get {
                return ResourceManager.GetString("RF10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agenzie viaggi e turismo (art.74-ter, DPR 633/72 ).
        /// </summary>
        public static string RF11 {
            get {
                return ResourceManager.GetString("RF11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agriturismo (art.5, c.2 L. 413/91 ).
        /// </summary>
        public static string RF12 {
            get {
                return ResourceManager.GetString("RF12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendite a domicilio (art.25-bis, c.6, DPR 600/73 ).
        /// </summary>
        public static string RF13 {
            get {
                return ResourceManager.GetString("RF13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rivendita beni usati, oggetti d&apos;arte, d&apos;antiquariato o da collezione (art.36, DL 41/95 ).
        /// </summary>
        public static string RF14 {
            get {
                return ResourceManager.GetString("RF14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agenzie di vendite all&apos;asta di oggetti d&apos;arte, antiquariato o da collezione (art.40-bis, DL 41/95 ).
        /// </summary>
        public static string RF15 {
            get {
                return ResourceManager.GetString("RF15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IVA per cassa P.A. (art.6, c.5, DPR 633/72 ).
        /// </summary>
        public static string RF16 {
            get {
                return ResourceManager.GetString("RF16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IVA per cassa (art. 32-bis, DL 83/2012).
        /// </summary>
        public static string RF17 {
            get {
                return ResourceManager.GetString("RF17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Altro.
        /// </summary>
        public static string RF18 {
            get {
                return ResourceManager.GetString("RF18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regime forfettario (art.1, c.54-89, L. 190/2014 ).
        /// </summary>
        public static string RF19 {
            get {
                return ResourceManager.GetString("RF19", resourceCulture);
            }
        }
    }
}
