//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FatturaElettronica.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TipoRitenuta {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TipoRitenuta() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FatturaElettronica.Resources.TipoRitenuta", typeof(TipoRitenuta).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ritenuta persone fisiche.
        /// </summary>
        public static string RT01 {
            get {
                return ResourceManager.GetString("RT01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ritenuta persone giuridiche.
        /// </summary>
        public static string RT02 {
            get {
                return ResourceManager.GetString("RT02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to contributo INPS.
        /// </summary>
        public static string RT03 {
            get {
                return ResourceManager.GetString("RT03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to contributo ENASARCO.
        /// </summary>
        public static string RT04 {
            get {
                return ResourceManager.GetString("RT04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to contributo ENPAM.
        /// </summary>
        public static string RT05 {
            get {
                return ResourceManager.GetString("RT05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to altro contributo previdenziale.
        /// </summary>
        public static string RT06 {
            get {
                return ResourceManager.GetString("RT06", resourceCulture);
            }
        }
    }
}
