//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FatturaElettronica.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TipoDocumento {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TipoDocumento() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("FatturaElettronica.Resources.TipoDocumento", typeof(TipoDocumento).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string TD01 {
            get {
                return ResourceManager.GetString("TD01", resourceCulture);
            }
        }
        
        public static string TD02 {
            get {
                return ResourceManager.GetString("TD02", resourceCulture);
            }
        }
        
        public static string TD03 {
            get {
                return ResourceManager.GetString("TD03", resourceCulture);
            }
        }
        
        public static string TD04 {
            get {
                return ResourceManager.GetString("TD04", resourceCulture);
            }
        }
        
        public static string TD05 {
            get {
                return ResourceManager.GetString("TD05", resourceCulture);
            }
        }
        
        public static string TD06 {
            get {
                return ResourceManager.GetString("TD06", resourceCulture);
            }
        }
        
        public static string TD16 {
            get {
                return ResourceManager.GetString("TD16", resourceCulture);
            }
        }
        
        public static string TD17 {
            get {
                return ResourceManager.GetString("TD17", resourceCulture);
            }
        }
        
        public static string TD18 {
            get {
                return ResourceManager.GetString("TD18", resourceCulture);
            }
        }
        
        public static string TD19 {
            get {
                return ResourceManager.GetString("TD19", resourceCulture);
            }
        }
        
        public static string TD20 {
            get {
                return ResourceManager.GetString("TD20", resourceCulture);
            }
        }
        
        public static string TD21 {
            get {
                return ResourceManager.GetString("TD21", resourceCulture);
            }
        }
        
        public static string TD22 {
            get {
                return ResourceManager.GetString("TD22", resourceCulture);
            }
        }
        
        public static string TD23 {
            get {
                return ResourceManager.GetString("TD23", resourceCulture);
            }
        }
        
        public static string TD24 {
            get {
                return ResourceManager.GetString("TD24", resourceCulture);
            }
        }
        
        public static string TD25 {
            get {
                return ResourceManager.GetString("TD25", resourceCulture);
            }
        }
        
        public static string TD26 {
            get {
                return ResourceManager.GetString("TD26", resourceCulture);
            }
        }
        
        public static string TD27 {
            get {
                return ResourceManager.GetString("TD27", resourceCulture);
            }
        }
        
        public static string TD28 {
            get {
                return ResourceManager.GetString("TD28", resourceCulture);
            }
        }
        
        public static string TD29 {
            get {
                return ResourceManager.GetString("TD29", resourceCulture);
            }
        }
    }
}
