//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FatturaElettronica.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TipoDocumento {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TipoDocumento() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FatturaElettronica.Resources.TipoDocumento", typeof(TipoDocumento).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fattura.
        /// </summary>
        internal static string TD01 {
            get {
                return ResourceManager.GetString("TD01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to acconto/anticipo su fattura.
        /// </summary>
        internal static string TD02 {
            get {
                return ResourceManager.GetString("TD02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to acconto/anticipo su parcella.
        /// </summary>
        internal static string TD03 {
            get {
                return ResourceManager.GetString("TD03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nota di credito.
        /// </summary>
        internal static string TD04 {
            get {
                return ResourceManager.GetString("TD04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nota di debito.
        /// </summary>
        internal static string TD05 {
            get {
                return ResourceManager.GetString("TD05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to parcella.
        /// </summary>
        internal static string TD06 {
            get {
                return ResourceManager.GetString("TD06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to integrazione fattura reverse charge interno.
        /// </summary>
        internal static string TD16 {
            get {
                return ResourceManager.GetString("TD16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to integrazione/autofattura per acquisto servizi dall&apos;estero.
        /// </summary>
        internal static string TD17 {
            get {
                return ResourceManager.GetString("TD17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to integrazione per acquisto di beni intracomunitari.
        /// </summary>
        internal static string TD18 {
            get {
                return ResourceManager.GetString("TD18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to integrazione/autofattura per acquisto di beni ex art. 17 c.2 DPR 633/72.
        /// </summary>
        internal static string TD19 {
            get {
                return ResourceManager.GetString("TD19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to autofattura per regolarizzazione e integrazione delle fatture (ex art.6 c.8 d.lgs. 471/97  o  art.46 c.5 D.L. 331/93).
        /// </summary>
        internal static string TD20 {
            get {
                return ResourceManager.GetString("TD20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to autofattura per splafonamento.
        /// </summary>
        internal static string TD21 {
            get {
                return ResourceManager.GetString("TD21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to estrazione beni da Deposito IVA.
        /// </summary>
        internal static string TD22 {
            get {
                return ResourceManager.GetString("TD22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to estrazione beni da Deposito IVA con versamento dell&apos;IVA.
        /// </summary>
        internal static string TD23 {
            get {
                return ResourceManager.GetString("TD23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fattura differita di cui all’art.21, comma 4, terzo periodo lett. a) DPR 633/72.
        /// </summary>
        internal static string TD24 {
            get {
                return ResourceManager.GetString("TD24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fattura differita di cui all’art.21, comma 4, terzo periodo lett. b) DPR 633/72.
        /// </summary>
        internal static string TD25 {
            get {
                return ResourceManager.GetString("TD25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cessione di beni ammortizzabili e per passaggi interni (ex art.36 DPR 633/72).
        /// </summary>
        internal static string TD26 {
            get {
                return ResourceManager.GetString("TD26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fattura per autoconsumo o per cessioni gratuite senza rivalsa.
        /// </summary>
        internal static string TD27 {
            get {
                return ResourceManager.GetString("TD27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to acquisti da San Marino con IVA (fattura cartacea).
        /// </summary>
        internal static string TD28 {
            get {
                return ResourceManager.GetString("TD28", resourceCulture);
            }
        }
    }
}
