//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FatturaElettronica.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TipoResa {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TipoResa() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FatturaElettronica.Resources.TipoResa", typeof(TipoResa).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Costo e Nolo.
        /// </summary>
        public static string CFR {
            get {
                return ResourceManager.GetString("CFR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Costo, assicurazione e nolo.
        /// </summary>
        public static string CIF {
            get {
                return ResourceManager.GetString("CIF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trasporto e assicurazione pagati fino a.
        /// </summary>
        public static string CIP {
            get {
                return ResourceManager.GetString("CIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trasporto pagato fino a.
        /// </summary>
        public static string CPT {
            get {
                return ResourceManager.GetString("CPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reso a luogo di destinazione.
        /// </summary>
        public static string DAP {
            get {
                return ResourceManager.GetString("DAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reso sdoganato.
        /// </summary>
        public static string DDP {
            get {
                return ResourceManager.GetString("DDP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reso al luogo di destinazione scaricato.
        /// </summary>
        public static string DPU {
            get {
                return ResourceManager.GetString("DPU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Franco Fabbrica.
        /// </summary>
        public static string EXW {
            get {
                return ResourceManager.GetString("EXW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Franco lungo bordo.
        /// </summary>
        public static string FAS {
            get {
                return ResourceManager.GetString("FAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Franco Vettore.
        /// </summary>
        public static string FCA {
            get {
                return ResourceManager.GetString("FCA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Franco a bordo.
        /// </summary>
        public static string FOB {
            get {
                return ResourceManager.GetString("FOB", resourceCulture);
            }
        }
    }
}
