//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FatturaElettronica.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TipoCassa {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TipoCassa() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FatturaElettronica.Resources.TipoCassa", typeof(TipoCassa).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cassa nazionale previdenza e assistenza avvocati e procuratori legali.
        /// </summary>
        public static string TC01 {
            get {
                return ResourceManager.GetString("TC01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cassa previdenza dottori commercialisti.
        /// </summary>
        public static string TC02 {
            get {
                return ResourceManager.GetString("TC02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cassa previdenza e assistenza geometri.
        /// </summary>
        public static string TC03 {
            get {
                return ResourceManager.GetString("TC03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cassa nazionale previdenza e assistenza ingegneri e architetti liberi professionisti.
        /// </summary>
        public static string TC04 {
            get {
                return ResourceManager.GetString("TC04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cassa nazionale del notariato.
        /// </summary>
        public static string TC05 {
            get {
                return ResourceManager.GetString("TC05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cassa nazionale previdenza e assistenza ragionieri e periti commerciali.
        /// </summary>
        public static string TC06 {
            get {
                return ResourceManager.GetString("TC06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ente nazionale assistenza agenti e rappresentanti di commercio (ENASARCO).
        /// </summary>
        public static string TC07 {
            get {
                return ResourceManager.GetString("TC07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ente nazionale previdenza e assistenza consulenti del lavoro (ENPACL).
        /// </summary>
        public static string TC08 {
            get {
                return ResourceManager.GetString("TC08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ente nazionale previdenza e assistenza medici (ENPAM).
        /// </summary>
        public static string TC09 {
            get {
                return ResourceManager.GetString("TC09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ente nazionale previdenza e assistenza farmacisti (ENPAF).
        /// </summary>
        public static string TC10 {
            get {
                return ResourceManager.GetString("TC10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ente nazionale previdenza e assistenza veterinari (ENPAV).
        /// </summary>
        public static string TC11 {
            get {
                return ResourceManager.GetString("TC11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ente nazionale previdenza e assistenza impiegati dell&apos;agricoltura (ENPAIA).
        /// </summary>
        public static string TC12 {
            get {
                return ResourceManager.GetString("TC12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fondo previdenza impiegati imprese di spedizione e agenzie marittime.
        /// </summary>
        public static string TC13 {
            get {
                return ResourceManager.GetString("TC13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Istituto nazionale previdenza giornalisti italiani (INPGI).
        /// </summary>
        public static string TC14 {
            get {
                return ResourceManager.GetString("TC14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opera nazionale assistenza orfani sanitari italiani (ONAOSI).
        /// </summary>
        public static string TC15 {
            get {
                return ResourceManager.GetString("TC15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cassa autonoma assistenza integrativa giornalisti italiani (CASAGIT).
        /// </summary>
        public static string TC16 {
            get {
                return ResourceManager.GetString("TC16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ente previdenza periti industriali e periti industriali laureati (EPPI).
        /// </summary>
        public static string TC17 {
            get {
                return ResourceManager.GetString("TC17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ente previdenza e assistenza pluricategoriale (EPAP).
        /// </summary>
        public static string TC18 {
            get {
                return ResourceManager.GetString("TC18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ente nazionale previdenza e assistenza biologi (ENPAB).
        /// </summary>
        public static string TC19 {
            get {
                return ResourceManager.GetString("TC19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ente nazionale previdenza e assistenza professione infermieristica (ENPAPI).
        /// </summary>
        public static string TC20 {
            get {
                return ResourceManager.GetString("TC20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ente nazionale previdenza e assistenza psicologi (ENPAP).
        /// </summary>
        public static string TC21 {
            get {
                return ResourceManager.GetString("TC21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INPS.
        /// </summary>
        public static string TC22 {
            get {
                return ResourceManager.GetString("TC22", resourceCulture);
            }
        }
    }
}
