//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FatturaElettronica.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ValidatorMessages {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidatorMessages() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("FatturaElettronica.Resources.ValidatorMessages", typeof(ValidatorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string E00417 {
            get {
                return ResourceManager.GetString("E00417", resourceCulture);
            }
        }
        
        public static string E00425 {
            get {
                return ResourceManager.GetString("E00425", resourceCulture);
            }
        }
        
        public static string E00415 {
            get {
                return ResourceManager.GetString("E00415", resourceCulture);
            }
        }
        
        public static string E00418 {
            get {
                return ResourceManager.GetString("E00418", resourceCulture);
            }
        }
        
        public static string E00429 {
            get {
                return ResourceManager.GetString("E00429", resourceCulture);
            }
        }
        
        public static string E00419 {
            get {
                return ResourceManager.GetString("E00419", resourceCulture);
            }
        }
        
        public static string E00420 {
            get {
                return ResourceManager.GetString("E00420", resourceCulture);
            }
        }
        
        public static string E00423 {
            get {
                return ResourceManager.GetString("E00423", resourceCulture);
            }
        }
        
        public static string E00400 {
            get {
                return ResourceManager.GetString("E00400", resourceCulture);
            }
        }
        
        public static string E00411 {
            get {
                return ResourceManager.GetString("E00411", resourceCulture);
            }
        }
        
        public static string E00422 {
            get {
                return ResourceManager.GetString("E00422", resourceCulture);
            }
        }
        
        public static string E00474 {
            get {
                return ResourceManager.GetString("E00474", resourceCulture);
            }
        }
        
        public static string E00476 {
            get {
                return ResourceManager.GetString("E00476", resourceCulture);
            }
        }
        
        public static string E00475 {
            get {
                return ResourceManager.GetString("E00475", resourceCulture);
            }
        }
        
        public static string E00471 {
            get {
                return ResourceManager.GetString("E00471", resourceCulture);
            }
        }
        
        public static string E00472 {
            get {
                return ResourceManager.GetString("E00472", resourceCulture);
            }
        }
        
        public static string E00473 {
            get {
                return ResourceManager.GetString("E00473", resourceCulture);
            }
        }
        
        public static string E00443 {
            get {
                return ResourceManager.GetString("E00443", resourceCulture);
            }
        }
        
        public static string E00444 {
            get {
                return ResourceManager.GetString("E00444", resourceCulture);
            }
        }
        
        public static string E00401 {
            get {
                return ResourceManager.GetString("E00401", resourceCulture);
            }
        }
        
        public static string E00430 {
            get {
                return ResourceManager.GetString("E00430", resourceCulture);
            }
        }
        
        public static string E00437 {
            get {
                return ResourceManager.GetString("E00437", resourceCulture);
            }
        }
        
        public static string ValidNumberRange_X_Y {
            get {
                return ResourceManager.GetString("ValidNumberRange_X_Y", resourceCulture);
            }
        }
        
        public static string DatiBeniServiziEObbligatorio {
            get {
                return ResourceManager.GetString("DatiBeniServiziEObbligatorio", resourceCulture);
            }
        }
        
        public static string IdentificativiFiscaliEObbligatorio {
            get {
                return ResourceManager.GetString("IdentificativiFiscaliEObbligatorio", resourceCulture);
            }
        }
        
        public static string E00418_S {
            get {
                return ResourceManager.GetString("E00418_S", resourceCulture);
            }
        }
        
        public static string E00401_S {
            get {
                return ResourceManager.GetString("E00401_S", resourceCulture);
            }
        }
        
        public static string E00400_S {
            get {
                return ResourceManager.GetString("E00400_S", resourceCulture);
            }
        }
        
        public static string E00460 {
            get {
                return ResourceManager.GetString("E00460", resourceCulture);
            }
        }
        
        public static string E00471_S {
            get {
                return ResourceManager.GetString("E00471_S", resourceCulture);
            }
        }
        
        public static string E00417_S {
            get {
                return ResourceManager.GetString("E00417_S", resourceCulture);
            }
        }
        
        public static string PropertyName_valoriAccettati_AcceptedValues {
            get {
                return ResourceManager.GetString("PropertyName_valoriAccettati_AcceptedValues", resourceCulture);
            }
        }
        
        public static string TestoContententeCaratteriNonValidi {
            get {
                return ResourceManager.GetString("TestoContententeCaratteriNonValidi", resourceCulture);
            }
        }
    }
}
